resource.AddFile( "materials/sprites/scope.vmt" )
resource.AddFile( "materials/sprites/scope.vtf" )
resource.AddFile( "materials/vgui/tdm/muted.png" )
resource.AddFile( "materials/vgui/tdm/unmuted.png" )
resource.AddFile( "resource/fonts/CODE Bold.otf" )
resource.AddFile( "resource/fonts/CODE Light.otf" )
resource.AddFile( "resource/fonts/cs.ttf" )
resource.AddFile( "resource/fonts/csd.ttf" )
resource.AddFile( "resource/fonts/cstrike.ttf" )
resource.AddFile( "resource/fonts/software_tester_7.ttf" )
resource.AddFile( "resource/fonts/Triomphe-Bold-Italic.otf" )
resource.AddFile( "resource/fonts/Triomphe-Bold.otf" )
resource.AddFile( "resource/fonts/Triomphe-Italic.otf" )
resource.AddFile( "resource/fonts/Triomphe-Light-Italic.otf" )
resource.AddFile( "resource/fonts/Triomphe-Light.otf" )
resource.AddFile( "resource/fonts/Triomphe-Regular.otf" )
resource.AddFile( "sound/tdm/blue/blue01.mp3" )
resource.AddFile( "sound/tdm/draw/draw01.mp3" )
resource.AddFile( "sound/tdm/headshotkill.mp3" )
resource.AddFile( "sound/tdm/hitmarker.wav" )
resource.AddFile( "sound/tdm/levelup.mp3" )
resource.AddFile( "sound/tdm/red/red01.mp3" )
resource.AddFile( "sound/ttt/thump01e.mp3" )
resource.AddFile( "sound/ttt/thump02e.mp3" )
resource.AddFile( "sound/ui/ui_menu_flip_single_02.wav" )