function pickClass( ply )
	local ChooseClassFrame = vgui.Create( "DFrame" )
	ChooseClassFrame:SetSize(ScrW()*0.6, ScrH()*0.6)
	ChooseClassFrame:SetTitle("Welcome. Please Choose a Class.")
	ChooseClassFrame:Center()
	ChooseClassFrame:SetVisible( true )
	ChooseClassFrame:SetDraggable( false )
	ChooseClassFrame:ShowCloseButton( true )
	ChooseClassFrame:MakePopup()
	ChooseClassFrame.startTime = SysTime()
	ChooseClassFrame.Paint = function()
		Derma_DrawBackgroundBlur(ChooseClassFrame, ChooseClassFrame.startTime)
	end

	local ChooseTeamSheet = vgui.Create( "DPropertySheet", ChooseClassFrame)
	ChooseTeamSheet:SetPos( 0, 25)
	ChooseTeamSheet:SetSize(ScrW()*0.6, ScrH()*0.6)
	ChooseTeamSheet.Paint = function()
		draw.RoundedBox( 8, 0, 0, ChooseTeamSheet:GetWide(), ChooseTeamSheet:GetTall(), Color(0,0,0,55))
	end

	SpectatorButton = vgui.Create('DButton')
	SpectatorButton:SetParent(ChooseTeamSheet)
	SpectatorButton:SetSize(100, 30)
	SpectatorButton:SetPos(0, 30)
	SpectatorButton:SetText('Assault')
	--SpectatorButton:SetFont("Team")
	--SpectatorButton:SetColor( Color( 255, 255, 255, 255 ) )
	SpectatorButton:SetDrawBackground(true)
	SpectatorButton.DoClick = function() 
		player_manager.SetPlayerClass( ply, "assault" )
		ply:Spawn()
		ChooseClassFrame:Close()
	end

	SpectatorButton = vgui.Create('DButton')
	SpectatorButton:SetParent(ChooseTeamSheet)
	SpectatorButton:SetSize(100, 30)
	SpectatorButton:SetPos(0, 60)
	SpectatorButton:SetText('Infantry')
	--SpectatorButton:SetFont("Team")
	--SpectatorButton:SetColor( Color( 255, 255, 255, 255 ) )
	SpectatorButton:SetDrawBackground(true)
	SpectatorButton.DoClick = function() 
		player_manager.SetPlayerClass( ply, "infantry" )
		ply:Spawn()
		ChooseClassFrame:Close()
	end
end
concommand.Add("pickClass", pickClass)